import "./globals.css";

export const metadata = {
  title: "Home",
  desciotion: "Generated by Create Naext App",
};

export default function Home() {
  return (
    <>
      <div className="mt-[450px] items-center">
        <h1 className=" text-center upprtcase text-2xl text-[#9e9e9e]">
          กรุณาทำสัญญาเช่าเพื่อเข้าถึงข้อมูล
        </h1>
      </div>
    </>
  );
}
